### ISSUE TITLE
FFMPEG::HTTPTooManyRequests when calling a URL for FFMPEG::Movie.New

### ISSUE THREAD

**Issue by alexholliz** [streamio/streamio-ffmpeg#154]
We're using the streamio-ffmpeg module in an attempt to transcode videos stored in our object store (provided by minio), with their URL as the input for ffmpeg. Here's a snippet of the code:

```
def transcode(link)
		url = link
		uri = URI.parse(url)
		source = FFMPEG::movie.new(uri.to_s)
		qualities.each do |q|
			mp4(source,q)
			webm(source,q)
		end
end
```

So we're pulling in "link", parsing it, and passing it to FFMPEG. That's where our error is generated.
Specifically, that `souce = FFMPEG::movie.new(uri,to_s)` line fails with FFMPEG::HTTPTooManyRequests

Is there something I am doing super wrong, or is this a bug with loading videos from URLs?

**Comment by bikeath1337** [comment]
TooManyRequests is a rate limiting response from the server that you're requesting the video from. The gem uses Net::HTTP check for redirects and follow them. Otherwise, we do a low-cost head to the url once and return the response. This is a sanity check. From there, we pass the url directly to FFMPeg for it to actually fetch the url.

So my first thought is if your remote is responding with too many requests, that's probably related to something else you're doing with them. Other processes... are you using job servers...the list could go on.

**Comment by alexholliz** [comment]
What we found was a limitation of our object store, Minio and it's interaction with rails. Running on the default port of 9000, the webserver was dropping any more than 10 requests at a time. Once we got SSL set up and enabled, and changed the port to 443, it ironed itself right out.
