### ISSUE TITLE
mp4 format for iMessage?

### ISSUE THREAD

**Issue by jvsu** [streamio/streamio-ffmpeg#205]
I've been able to create mp4 videos using this gem and it uploads without any issues to iPhoto, Twitter, iMovie, etc, but for some reason the same mp4 video is not able to be sent over iMessage. When I try to send an mp4 video I've generated with this gem it just causes iMessage to "hang" or stall.

It looks to me like there might be some sort of format issue with the MP4 video because I am able to send other MP4 videos not converted using this gem through iMessage successfully. 

Here is the options hash I am using:
options = {
video_codec: "libx264", frame_rate: 30, seek_time:start_time ,duration:duration, resolution:"640x360", audio_codec:"aac", audio_stream:"stereo", video_stream:"yuv420p", colorspace:"yuv420p"
}

Does anyone know the proper options to get a MP4 video that is compatible with iMessage? 
Can it be the ffmpeg version I'm using? 

Anything that can point me in the right direction would be appreciated.

**Comment by JohnnyMarnell** [comment]
i have same problem, tried mp4 + mov containers, you ever come up with anything?

**Comment by dcontiveros** [comment]
I believe I have managed to solve this issue. However, I would need to test with a sample video. Can you provide one @JohnnyMarnell ? I'm using FFmpeg nightly, and not streamio, so I would need a source file I can modify.

**Comment by jvsu** [comment]
Here is the source video: https://drive.google.com/open?id=1hU4-pudc4Gd4umJ3cDKu88Ar9bnjThcC

Then I created a clip using streamio-ffmpeg which iMessage won't send. 
Here's the clip: https://drive.google.com/open?id=1ZU_G_Cegd2dmUzg9xCfZN2PDqFAuswZT

This could be relevant, I am creating clips using a FFMPEG Heroku buildpack: https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest.git

So I don't know if I'm using the correct options hash for Streamio, if the FFMPEG buildpack is creating an incompatible video clip, or some other thing I'm not familiar with.

**Comment by dcontiveros** [comment]
Your test file only confirms my suspicion. The main issue is that iMessage expects the color primary metadata to be written into the file before it can be sent over an iMessage chat. To see the problem, you need two programs:

1. An ffmpeg distributable (I grabbed a nightly version for my OS)
2. mediainfo app (https://en.wikipedia.org/wiki/MediaInfo)

I personally have encountered this on HDR -> SDR conversion, but essentially, for whatever reason, ffmpeg does not write color profile by default. Here is what I did:

1. I downloaded the clip you made from the source video.
2. I compared the text output to a working file I have on my hard drive from a previous encounter of this issue. Mediainfo confirmed zero profiles were written into your clip.
3. I pulled up iMessage and attempted to send your clip. That failed.
4. Instead of reencoding, I used ffmpeg to insert the proper color profiles. I used the following command, which shows only insertion was made:

```
ffmpeg -i nonworking.mp4 \
-color_primaries bt709 \
-color_trc bt709 \
-colorspace bt709 \
-y \
test.mp4
```

5. Insertion took a few seconds. Mediainfo reports the following additional lines:

```
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709
```

6. Previewed the file via mpv to ensure quality
7. Attempted to send via iMessage. This sent right away since size was about 2MB.

I don't believe this is a streamio-ffmpeg file. I will let you confirm though. Thanks.

**Comment by jvsu** [comment]
You are correct. I re-encoded the non working video with the -color_primaries flag and it was successfully sent over iMessage. 

Do you know if streamio accepts color_primaries as an option to be transcoded? 

options = {
video_codec: "libx264", frame_rate: 30, seek_time:start_time ,duration:duration, resolution:"640x360", audio_codec:"aac", audio_stream:"stereo", video_stream:"yuv420p", colorspace:"bt709", **color_primaries:"bt709"** 
}, then movie.transcode("#{file_name}.mp4",**options**)

I've been trying to create video clips with streamio passing color_primaries as one of the options, but iMessage refuses to send it and it looks like streamio doesn't take it as an option.

**Comment by jvsu** [comment]
@dcontiveros you are definitely correct. It was just missing the color_primaries metadata. 

My problem was trying to create a trimmed clip and encode it with the color_primaries and other things all at once, but when I split this process into two parts it worked. First create the clip with options1 

options1 = {video_codec: "libx264", frame_rate: 30, seek_time:start_time ,duration:duration,resolution:"640x360",audio_codec:"aac", audio_stream:"stereo",video_stream:"yuv420p"
       }


then take the resulting clip and re-encode it with options2.

options2 = {vf:"format=yuv420p",**color_primaries:"bt709",**colorspace:"bt709"}

Afterwards, I ended up with a clip that could be sent over iMessage. 


Thanks
