### ISSUE TITLE
Project abandoned?

### ISSUE THREAD

**Issue by jetienne** [streamio/streamio-ffmpeg#223]
It looks like this project is not maintained anymore. Am I correct?

**Comment by rackfishdaniel** [comment]
You are correct. While we still use streamio-ffmpeg internally we're using an old branch for legacy reasons and we don't really have the resources to maintain streamio-ffmpeg for the community.

Many years back someone (bike) offered to maintain the project pro bono and created the 2.x version and handled bugs and merge requests while we still published the gem. He hasn't done anything since 2017 however but we appreciate everything he's done.

We'd certainly be open to hand over the reigns to someone else who felt like giving streamio-ffmpeg some TLC!
